// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:fcc7bbde-a654-49bf-a390-b93a7a22e526",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_6H2ER7mjP",
    "aws_user_pools_web_client_id": "6ggiu9lavu2jm2364jhqgto64g",
    "oauth": {},
    "aws_user_files_s3_bucket": "filterwordsfiles-react",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
